#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

useradd -m  -u 1000 -U -d  /home/developer developer
usermod -G www-data developer
exec "$@"
